home:
    path: /
    defaults:
        _controller: IcepiqueAppBundle:Default:index

listing_auto_login:
    path: /listings/{listingId}/auth/{token}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        listingId: \d+
        token: \w+
    options:
        utf8: true
        i18n: false

# Pseudo account actions for non-logged in users
my_saved_listings:
    path: /saved/items/listings
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

my_saved_searches:
    path: /saved/items/searches
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

my_listings:
    path: /listings/own
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

user:
    resource: "@IcepiqueAppBundle/Resources/config/routing/user.yml"

listing:
    resource: "@IcepiqueAppBundle/Resources/config/routing/listing.yml"

payment:
    resource: "@IcepiqueAppBundle/Resources/config/routing/payment.yml"

category:
    resource: "@IcepiqueAppBundle/Resources/config/routing/category.yml"

catalog:
    resource: "@IcepiqueAppBundle/Resources/config/routing/catalog.yml"

account:
    resource: "@IcepiqueAppBundle/Resources/config/routing/account.yml"

ajax:
    resource: "@IcepiqueAppBundle/Resources/config/routing/ajax.yml"

contact:
    path: /contact
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

contact_success:
    path: /contact/message-sent
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        template: "@IcepiqueBezplatno/contact/contact-success.html.twig"
    options:
        utf8: true

media_kit:
    path: /media-kit
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

user_agreement:
    path: /terms-and-conditions
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

privacy_policy:
    path: /privacy-policy
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

privacy_policy_consent:
    path: /account/privacy-policy/consent
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

verification_explained:
    path: /listing-verification
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

listings_by_city:
    path: /listings-by-city
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

companies_by_city:
    path: /companies-by-city
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

whats_new:
    path: /новости-в-сайта
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

faq:
    path: /faq
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

about_us:
    path: /about-us
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

statistics:
    path: /stats
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

anonymous_messages_view:
    path: /enquiry/{id}/{token}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        token: "[^/]+"
        id: \d+
    options:
        utf8: true
        i18n: false

# Login Options
login:
    resource: "@IcepiqueAppBundle/Resources/config/routing/login.yml"
# Facebook Deauthorize URL

facebook_deauthorize:
    path: /facebook/deauthorize
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: false
        i18n: false

# Fallback for legacy routing
legacy:
    resource: "@IcepiqueAppBundle/Resources/config/routing/legacy.yml"

# Email notification handling from AWS
amazon_sns_notifications:
    path: /email-notifications
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false
    methods: [POST]

# Content pages
page:
    path: /{slug}
    defaults:
        _controller: IcepiqueCoreBundle:Default:page