home:
    path: /
    host: "{domain}%base_domain%"
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        domain: "www"
    requirements:
        domain: "www|beta|staging"

user:
    resource: "@IcepiqueAppBundle/Resources/config/routing/user.yml"

category:
    resource: "@IcepiqueAppBundle/Resources/config/routing/category.yml"

user_subdomain:
    resource: "@IcepiqueAppBundle/Resources/config/routing/user_sub_domain.yml"