user_register:
    path: /registration
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

user_register_confirm:
    path: /registration/confirm/{id}/{token}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        id: \d+
        token: .+
    options:
        utf8: true

user_register_confirmed:
    path: /registration/confirmed
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

user_register_options:
    path: /registration/options
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

user_login:
    path: /login
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

user_login_reset_password:
    path: /reset-password
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

user_login_new_password:
    path: /new-password/{id}/{token}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

user_login_reset_password_check_email:
    path: /reset-password/check-email
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

user_register_check_email:
    path: /registration/check-email
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true