ajax_location_options:
    path: /ajax/location/options
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_location_region_cities:
    path: /ajax/location/region/{regionId}/cities
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        regionId: \d+
    options:
        i18n: false

ajax_location_city_areas:
    path: /ajax/location/city/{cityId}/areas
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        cityId: \d+
    options:
        i18n: false

ajax_category_list:
    path: /ajax/category/list
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_category_options:
    path: /ajax/category/view
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_category_attributes:
    path: /ajax/category/attributes/{categoryId}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        categoryId: \d+
    options:
        i18n: false

ajax_category_attributes_group:
    path: /ajax/category/attributes/group
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_saved_listings_add:
    path: /ajax/listings/saved/{listingId}/add
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        listingId: \d+
    options:
        i18n: false

ajax_saved_listings_remove:
    path: /ajax/listings/saved/{listingId}/remove
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        listingId: \d+
    options:
        i18n: false

ajax_listings_action:
    path: /ajax/listings/{action}/{id}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        id: \d+
        action: "(archive|remove|activate|hide)"
    options:
        i18n: false

ajax_listing_contact:
    path: /ajax/listings/message/{listingId}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        listingId: \d+
    options:
        i18n: false

ajax_saved_searches_add:
    path: /ajax/searches
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_saved_searches_remove:
    path: /ajax/searches/{searchId}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_user_send_message:
    path: /ajax/user/message/{conversationId}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        conversationId: \d+
    options:
        i18n: false

ajax_vip_access_code:
    path: /ajax/vip-access/{code}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_promo_code_validate:
    path: /ajax/promo-code
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_cookies_agreement:
    path: /ajax/cookies-agreement
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_check_computer_authorization:
    path: /ajax/computer-auth-token
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_payment_code:
    path: /ajax/payment-code/generate
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_search_autocomplete:
    path: /search/autocomplete
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_search_categories:
    path: /ajax/categories/list
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_search_locations:
    path: /ajax/cities/list
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_related_listings:
    path: /ajax/listings/{listingId}/related
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        listingId: \d+
    options:
        i18n: false

ajax_site_message:
    path: /ajax/site-message
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

listings_pictures_upload:
    path: /ajax/listings/pictures/{token}/upload
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

listings_pictures_remove:
    path: /ajax/listings/pictures/{token}/remove
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

listings_pictures_rotate:
    path: /ajax/listings/pictures/{token}/rotate
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

listings_pictures_reorder:
    path: /ajax/listings/pictures/{token}/reorder
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

catalog_pictures_upload:
    path: /ajax/catalog/pictures/{token}/upload
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

catalog_pictures_remove:
    path: /ajax/catalog/pictures/{token}/remove
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

catalog_pictures_rotate:
    path: /ajax/catalog/pictures/{token}/rotate
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

catalog_pictures_reorder:
    path: /ajax/catalog/pictures/{token}/reorder
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

user_pictures_upload:
    path: /ajax/user/pictures/{type}/upload
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        type: "^cover|profile"
    options:
        i18n: false

user_pictures_remove:
    path: /ajax/user/pictures/{type}/remove
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        type: "^cover|profile$"
    options:
        i18n: false

user_pictures_cover_position:
    path: /ajax/user/pictures/position
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_moderation_flag_check:
    path: /ajax/moderation/{sessionId}/{listingId}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        listingId: null
    requirements:
        listingId: \d+
    options:
        i18n: false

ajax_verification_create:
    path: /ajax/verification/create
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false


ajax_verification_check:
    path: /ajax/verification/check
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_delivery_cities:
    path: /ajax/delivery/cities
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_delivery_streets:
    path: /ajax/delivery/streets
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false

ajax_delivery_areas:
    path: /ajax/delivery/areas
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        i18n: false