# Legacy path for listings
legacy_listing:
    path: /listing-{id}-{slug}.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        id: \d+
        slug: "[^/]+"

legacy_my_listings:
    path: /my_listings
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: my_listings
    options:
        utf8: true

legacy_listings_base:
    path: /обяви
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: home
    options:
        utf8: true

# Legacy path for category
legacy_category:
    path: /categories-{id}-{slug}.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        id: \d+
        slug: ".*"

# Legacy path for catalog listings
legacy_catalog_listing:
    path: /catalog-listing-{id}-{slug}.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        id: \d+
        slug: ".*"

# Legacy path for catalog category
legacy_catalog_category:
    path: /catalog-{id}-{slug}.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        id: \d+
        slug: "[^/]+"

# Legacy path for sections
legacy_listing_contact:
    path: /обяви/{slug}-{id}/contact.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: listing
    options:
        utf8: true
    requirements:
        id: \d+
        slug: "[^/]+"

legacy_listing_send_to_friend:
    path: /обяви/{slug}-{id}/send_friend.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: listing_share
    options:
        utf8: true
    requirements:
        id: \d+
        slug: "[^/]+"

legacy_listing_gallery:
    path: /обяви/{slug}-{id}/gallery.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: listing
    options:
        utf8: true
    requirements:
        id: \d+
        slug: "[^/]+"

legacy_listing_problem:
    path: /обяви/{slug}-{id}/problem.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: listing_problem
    options:
        utf8: true
    requirements:
        id: \d+
        slug: "[^/]+"

legacy_listing_comments:
    path: /обяви/{slug}-{id}/comments.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: listing
    options:
        utf8: true
    requirements:
        id: \d+
        slug: "[^/]+"

legacy_listing_upgrade:
    path: /обяви/{slug}-{id}/{upgrade}.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: listing_upgrade
        permanent: true
        ignoreAttributes:
            - upgrade
    options:
        utf8: true
    requirements:
        id: \d+
        slug: "[^/]+"
        upgrade: "vip|super"

# Legacy path for catalog sections
legacy_catalog_listing_contact:
    path: /каталог-фирми/{slug}-{id}/contact.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: catalog_listing_contact
    options:
        utf8: true
    requirements:
        id: \d+
        slug: "[^/]+"

legacy_catalog_listing_send_to_friend:
    path: /каталог-фирми/{slug}-{id}/send_friend.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: catalog_listing_share
    options:
        utf8: true
    requirements:
        id: \d+
        slug: "[^/]+"

legacy_catalog_listing_gallery:
    path: /каталог-фирми/{slug}-{id}/gallery.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: catalog_listing
    options:
        utf8: true
    requirements:
        id: \d+
        slug: "[^/]+"

legacy_catalog_listing_comments:
    path: /каталог-фирми/{slug}-{id}/comments.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: catalog_listing
    options:
        utf8: true
    requirements:
        id: \d+
        slug: "[^/]+"

legacy_catalog_listing_problem:
    path: /каталог-фирми/{slug}-{id}/problem.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: catalog_listing_problem
    options:
        utf8: true
    requirements:
        id: \d+
        slug: "[^/]+"

legacy_catalog_listing_upgrade:
    path: /каталог-фирми/{slug}-{id}/vip.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: catalog_listing_upgrade
    options:
        utf8: true
    requirements:
        id: \d+
        slug: "[^/]+"

# Legacy paths to old pages
legacy_listing_publish:
    path: /publish.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: listing_add

legacy_listing_update:
    path: /edit.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index

legacy_forgot_password:
    path: /forgot_password.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: listing_reset_password

legacy_catalog_listing_publish:
    path: /catalog_publish.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: catalog_listing_add

legacy_catalog_listing_update:
    path: /catalog_edit.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: catalog_listing_login

legacy_catalog_forgot_password:
    path: /catalog_forgot_password.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: catalog_listing_reset_password

legacy_faq:
    path: /faq.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: faq

legacy_advertise:
    path: /advertise.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: media_kit

legacy_statistics:
    path: /stats.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: statistics

legacy_contact_us:
    path: /contact.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: contact

legacy_contact_us_form:
    path: /contact_us.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: contact

legacy_contact_problem:
    path: /contact_problem.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: contact

legacy_merchants_registration:
    path: /merchants.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: user_register

legacy_new_registration:
    path: /register.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: user_register

legacy_account_forgot_password:
    path: /forgot_password_account.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: user_login_reset_password

legacy_favourites:
    path: /favorites.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: my_saved_listings

legacy_catalog_favourites:
    path: /catalog_favorites.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: my_saved_listings

legacy_policy:
    path: /policy.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: user_agreement

legacy_cities:
    path: /cities.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: listings_by_city

legacy_catalog_cities:
    path: /catalog_cities.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: companies_by_city

# Legacy path for home page
legacy_home:
    path: /index.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        route: home