listing_shortcut:
    path: /{id}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        id: \d+

listing:
    path: /обяви/{slug}-{id}.html
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true
    requirements:
        slug: "[^/]+"
        id: \d+

listing_print:
    path: /обяви/{slug}-{id}/принтирай
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true
    requirements:
        slug: "[^/]+"
        id: \d+

listing_flyer:
    path: /обяви/{slug}-{id}/отпечатай
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true
    requirements:
        slug: "[^/]+"
        id: \d+

listing_share:
    path: /обяви/{slug}-{id}/изпрати-на-приятел
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true
    requirements:
        slug: "[^/]+"
        id: \d+

listing_gallery:
    path: /обяви/{slug}-{id}/снимки
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true
    requirements:
        slug: "[^/]+"
        id: \d+

listing_problem:
    path: /обяви/{slug}-{id}/докладвай-проблем
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true
    requirements:
        slug: "[^/]+"
        id: \d+

listing_problem_contact_success:
    path: /обяви/{slug}-{id}/успешно-докладван-проблем
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        template: "@IcepiqueBezplatno/listing/contact/problem-success.html.twig"
    options:
        utf8: true
    requirements:
        slug: "[^/]+"
        id: \d+

listing_upgrade:
    path: /обяви/{slug}-{id}/промотирай
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true
    requirements:
        slug: "[^/]+"
        id: \d+

listing_offer:
    path: /обяви/{slug}-{id}/оферта
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true
    requirements:
        slug: "[^/]+"
        id: \d+

listing_search:
    path: /search
    defaults:
        _controller: IcepiqueAppBundle:Default:index

listing_login:
    path: /listings/login
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

listing_logout:
    path: /listings/logout/{id}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        id: \d+
    options:
        utf8: true

listing_reset_password:
    path: /listings/reset-password
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

listing_new_password:
    path: /listings/new-password/{id}/{token}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        id: \d+
    options:
        utf8: true

listing_reset_password_check_email:
    path: /listings/reset-password/check-email
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

listing_add:
    path: /listings/add
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

listing_update:
    path: /listings/update/{id}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        id: \d+
    options:
        utf8: true

listing_delete:
    path: /listings/delete/{id}
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        id: \d+
    options:
        utf8: true

listing_delete_success:
    path: /обяви/{id}/обявата-изтрита-успешно
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        id: \d+
    options:
        utf8: true

listing_preview:
    path: /listings/preview
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

listing_publish_success:
    path: /обяви/успешно-публикуване
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

listing_update_success:
    path: /обяви/успешно-обновяване
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    options:
        utf8: true

listing_verification_image:
    path: /images/{listingId}/{token}.png
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        listingId: \d+
        token: "[^/]+"
    options:
        i18n: false

listing_renewal:
    path: /обяви/{id}/поднови-обява
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        id: \d+
    options:
        utf8: true

listing_renewal_success:
    path: /обяви/{id}/успешно-подновяване
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        id: \d+
    options:
        utf8: true