subdomain_public:
    path: /
    host: "{domain}%base_domain%"
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        domain: ".*"
    options:
        utf8: true

subdomain_listings:
    path: /listings
    host: "{domain}%base_domain%"
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        domain: ".*"
    options:
        utf8: false

subdomain_contact:
    path: /contact
    host: "{domain}%base_domain%"
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        domain: ".*"
    options:
        utf8: true

subdomain_listings_category:
    path: /listings/{categorySlug}
    host: "{domain}%base_domain%"
    defaults:
        _controller: IcepiqueAppBundle:Default:index
        categorySlug: ''
    requirements:
        domain: ".*"
        categorySlug: "[\\D]+"
    options:
        utf8: true

subdomain_feedback:
    path: /feedback
    host: "{domain}%base_domain%"
    defaults:
        _controller: IcepiqueAppBundle:Default:index
    requirements:
        domain: ".*"
    options:
        utf8: true